media:
  input: images
  output: /images

content:
  - name: members
    label: Members
    type: collection
    path: _members
    format: yaml-frontmatter

    filename:
      template: "{primary}.md"
      field: create

    view:
      primary: name
      fields:
        - name
        - role
        - affiliation

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: image
        label: Profile Image
        type: image

      - name: role
        label: Role
        type: string

      - name: affiliation
        label: Affiliation
        type: string

      - name: aliases
        label: Aliases
        type: string
        list: true

      - name: links
        label: Links
        type: object
        fields:
          - name: home-page
            label: Homepage
            type: string

          - name: orcid
            label: ORCID
            type: string

          - name: google-scholar
            label: Google Scholar
            type: string

          - name: github
            label: GitHub
            type: string

      - name: body
        label: Biography
        type: rich-text